### ISSUE TITLE
GPU accelerated dead leaves generator

### ISSUE THREAD

**Issue by Jamy-L** [balthazarneveu/blind-deblurring-from-synthetic-data#16]
The current generator is currently very slow, as it requires to compute a high resolution image and downsample it by a factor of up to 5. 

A solution is to implement that using numba kernels to use the GPU.

To do:
- [x] Generate the HR image using numba device arrays
- [x] Convert to pytorch and apply anti-aliased downsample
- [x] Convert numba to pytorch gpu tensors on the fly

**Comment by Jamy-L** [comment]
The new dataset is working but not connected yet. The speedup is roughly x2, and the memory cost is very low.

**Comment by balthazarneveu** [comment]
- [ ] add pytest

**Comment by Jamy-L** [comment]
- Pytest added for the new dataset, plus a new test with a short gpu vs cpu benchmark. These tests are skipped if cuda is not installed (`numba.cuda.is_available()`).

- Fixed a bug for `ds=1` that crashed the GPU dataloader !

- The dataloader in grey mode will now output shape [h, w, 1] instead of shape [h, w, 3] (duplicated channel). The visualisation may need adjustments
