### ISSUE TITLE
GPU accelerated non uniform blur

### ISSUE THREAD

**Issue by Jamy-L** [balthazarneveu/blind-deblurring-from-synthetic-data#17]
Generating non uniform blur cannot easily be done using pytorch. A numba kernel is required to perform the degradation operation.

- [ ] Sample realistic non uniform blur kernel
- [ ] Apply the non uniform blur
- [ ] Add an oprion to use uniform or non uniform blur

**Comment by balthazarneveu** [comment]
Not planned because we keep with the uniform deblur problem
