### ISSUE TITLE
Deadleave dataloader

### ISSUE THREAD

**Issue by balthazarneveu** [balthazarneveu/blind-deblurring-from-synthetic-data#2]
:warning:  No downscaling so far, the patches shall be generated at a higher resolution then downscaled (factor 5) with gaussian blur first according to the paper! (yes first version is full of aliasing in the disk)

No downsampling 2 minutes/epoch on Kaggle :rocket:  
:warning:  When downsampling = 5 -> 20 minutes / epoch on Kaggle 

- [ ] Downsampling!
- [ ] improve color sampling (more realistic colors - lower color contrasts to make it difficult like blue deadleaves)
 
:bulb:  does this really matter ? prior may learn the  most probable colors but since this is a pure modelization of the world... this should almost be agnostic to colors and rather relie on shape)

Natural colors: 
> The color distribution of the disks is given by the histograms of the natural images from the Waterloo database [19].
 
# Performances and options

> Generation on CPU seems quite fast. Maybe a profiling would be good

Check best possibility:
- Dataloader on CPU 
- Dataloader with torch / Cuda kernel directly on GPU
- Pre-save a bunch of images to disk

# Degradation model
- Should we merge the blur/degradation when splatting? (analytical blur on an analytic circle) -> requires a cuda kernel in this case.
- Anisotropic kernels (angle etc..) . Other than Gaussian?
- Non uniform blurs
- Return oracle (non blind)

**Comment by Jamy-L** [comment]
The following options seem like a good approach:

- [ ] Write a numba kernel to generate the HR deadleaves model
- [ ] Do the anti-aliased downsampling (this can efficiently be achieve with a strided convolution, uisng pytorch for example)
- [ ] Write a numba kernel to apply any uniform degradation blur (To prepare what comes next).
- [ ] Write a numba kernel to apply any non-uniform degradation blur (should be easy once the previous step is done).
- [ ] Plug numba and pytorch to convert the GPU tensor on the fly
- [ ] Implement a generator that picks a realistic non uniform blur kernel field.

One element that is not crystal clear right now is what represention we should give to the numba kernel. Should we go parametric and give a field of std/covariance, or instead give a field of 2d arrays defining the local kernel blur.
